name: Automatic Word Drop

on:
  schedule:
    - cron: "30 0 * * *"  
  workflow_dispatch:

jobs:
  run_word_drop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create credentials.json
        run: echo '${{ secrets.GOOGLE_CREDENTIALS_JSON }}' > credentials.json

      - name: Create token.json
        run: echo '${{ secrets.GOOGLE_TOKEN_JSON }}' > token.json

      - name: Run the main automation script
        run: python main.py
        env:
          G_TOKEN: ${{ secrets.GH_PAT }}

